/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AllowanceModule } from "./AllowanceModule";
export * as factories from "./factories";
export { AllowanceModule__factory } from "./factories/AllowanceModule__factory";
